version: '3'
services:
  actc:
    build:
      context: .
      dockerfile: ./docker/actc/Dockerfile
    expose:
      - "80"
    links:
      - mysql
      - portal
      - ra_manager
      - renewability_manager
    security_opt:
      - seccomp=unconfined # Allow gdb debugging
    volumes:
      - "./projects:/projects"
      - "build:/build"
      - "online_backends:/opt/online_backends"
      - "root_home:/root"
    working_dir: "/projects"
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=aspire
    image: mysql:5.5
    expose:
      - "3306"
    # Set up databases.
    volumes:
      - "./modules/remote_attestation/setup/:/docker-entrypoint-initdb.d/remote_attestation"
      - "./modules/renewability/setup/:/docker-entrypoint-initdb.d/renewability"
      - "./docker/mysql/mysql-setup.sh:/docker-entrypoint-initdb.d/setup.sh"
  portal:
    build:
      context: .
      dockerfile: ./docker/portal/Dockerfile
    links:
      - mysql
    ports:
      - "8088:80"
    volumes:
      - "online_backends:/opt/online_backends"
  ra_manager:
    build:
      context: .
      dockerfile: ./modules/remote_attestation/Dockerfile
    links:
      - mysql
    ports:
      - "8090-8099:8090-8099"
    volumes:
      - "online_backends:/opt/online_backends"
  renewability_manager:
    build:
      context: .
      dockerfile: ./modules/renewability/Dockerfile
    links:
      - mysql
    ports:
      - "18001:18001"
    volumes:
      - "online_backends:/opt/online_backends"
volumes:
  build:
  online_backends:
  root_home:
