version: '3'
services:
  aspire:
    build: .
    ports:
      - "8080-8099:8080-8099"
      - "18001:18001"
    volumes:
      - "./projects:/projects"
      - "root_home:/root"
    working_dir: "/projects"
volumes:
  root_home:
