version: '3'
services:
  aspire:
    build: .
    ports:
      - "8080-8099:8080-8099"
      - "18001:18001"
    security_opt:
      - seccomp=unconfined # Allow gdb debugging
    volumes:
      - "./projects:/projects"
      - "build:/build"
      - "online_backends:/opt/online_backends"
      - "root_home:/root"
    working_dir: "/projects"
volumes:
  build:
  online_backends:
  root_home:
